# Generated by Django 3.0.7 on 2020-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_device', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(default='SOLD', max_length=200)),
                ('issue', models.CharField(default='No issue', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_device', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(default='SOLD', max_length=200)),
                ('issue', models.CharField(default='No issue', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_device', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('status', models.CharField(default='SOLD', max_length=200)),
                ('issue', models.CharField(default='No issue', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
